services:
  - type: web
    name: waha-core
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /swagger
    envVars:
      - key: WHATSAPP_API_PORT
        value: 3000
      - key: WHATSAPP_API_HOSTNAME
        value: 0.0.0.0
      - key: PORT
        value: 3000
      - key: WAHA_API_KEY
        value: ""
      - key: WAHA_NO_API_KEY
        value: "True"
      - key: WAHA_DASHBOARD_NO_PASSWORD
        value: "True"
      - key: WHATSAPP_SWAGGER_NO_PASSWORD
        value: "True"
      - key: WAHA_PRINT_QR
        value: "True"
      - key: WAHA_LOG_FORMAT
        value: PRETTY
      - key: WAHA_LOG_LEVEL
        value: info
