services:
  - type: web
    name: waha-core
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /swagger
    envVars:
      - key: WHATSAPP_API_PORT
        value: 3000
      - key: WAHA_DASHBOARD_USERNAME
        value: admin
      - key: WAHA_DASHBOARD_PASSWORD
        value: admin
      - key: WHATSAPP_SWAGGER_USERNAME
        value: admin
      - key: WHATSAPP_SWAGGER_PASSWORD
        value: admin
      - key: WAHA_PRINT_QR
        value: "True"
      - key: WAHA_LOG_FORMAT
        value: PRETTY
      - key: WAHA_LOG_LEVEL
        value: info
